# Generated by Django 2.0.1 on 2020-05-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200504_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='theses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Student')),
                ('teacher', models.ForeignKey(default='hamidabdoli', on_delete=django.db.models.deletion.CASCADE, to='first.Teacher')),
            ],
        ),
    ]
